server:
  port: 80

spring:
  mail:
    host: smtp.163.com
    username: zhzh2048@163.com
    password: Q13626172055qq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true